// This file is auto-generated by @hey-api/openapi-ts

export const ConfigSchema = {
    properties: {
        version: {
            type: 'string',
            pattern: '(\\d+(\\.\\d+){0,2}|\\d+\\.\\d+\\.[a-z0-9]+\\+[a-z0-9.]+)',
            title: 'Version'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        created_by: {
            type: 'string',
            title: 'Created By'
        }
    },
    type: 'object',
    required: ['version', 'created_at', 'created_by'],
    title: 'Config',
    description: `The configuration file in a .fmu directory.

Stored as config.json.`
} as const;

export const FMUDirPathSchema = {
    properties: {
        path: {
            type: 'string',
            format: 'path',
            title: 'Path'
        }
    },
    type: 'object',
    required: ['path'],
    title: 'FMUDirPath',
    description: 'Path where a .fmu directory may exist.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;