// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8001' | (string & {});
};

/**
 * APIKey
 *
 * A key-value pair for a known and supported API.
 */
export type ApiKey = {
    /**
     * Id
     */
    id: string;
};

/**
 * Access
 *
 * The ``access`` block contains information related to access control for
 * this data object.
 */
export type Access = {
    asset: Asset;
    classification?: Classification | null;
};

/**
 * AccessToken
 *
 * A key-value pair for a known and supported access scope.
 */
export type AccessToken = {
    /**
     * Id
     */
    id: string;
};

/**
 * Asset
 *
 * The ``access.asset`` block contains information about the owner asset of
 * these data.
 */
export type Asset = {
    /**
     * Name
     */
    name: string;
};

/**
 * CacheContent
 *
 * Content of a cache revision.
 */
export type CacheContent = {
    /**
     * Data
     *
     * Parsed JSON object for the cached resource.
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * CacheList
 *
 * List of cache revision filenames.
 */
export type CacheList = {
    /**
     * Revisions
     *
     * Cache revision filenames, sorted oldest to newest.
     */
    revisions: Array<string>;
};

/**
 * CacheResource
 *
 * Resources that can be cached and restored.
 */
export type CacheResource = 'config.json' | 'mappings.json';

/**
 * CacheRetention
 *
 * Cache retention setting for project resources.
 */
export type CacheRetention = {
    /**
     * Cache Max Revisions
     *
     * Maximum number of cache revisions to keep per resource.
     */
    cache_max_revisions?: number;
};

/**
 * ChangeInfo
 *
 * Represents a change in the changelog file.
 */
export type ChangeInfo = {
    /**
     * Timestamp
     */
    timestamp?: string;
    change_type: ChangeType;
    /**
     * User
     */
    user: string;
    /**
     * Path
     */
    path: string;
    /**
     * Change
     */
    change: string;
    /**
     * Hostname
     */
    hostname: string;
    /**
     * File
     */
    file: string;
    /**
     * Key
     */
    key: string;
};

/**
 * ChangeType
 *
 * The types of change that can be made on a file.
 */
export type ChangeType = 'init' | 'update' | 'remove' | 'add' | 'reset' | 'restore' | 'merge' | 'copy';

/**
 * Classification
 *
 * The security classification for a given data object.
 */
export type Classification = 'asset' | 'internal' | 'restricted';

/**
 * CoordinateSystem
 *
 * The ``masterdata.smda.coordinate_system`` block contains the coordinate
 * system known to SMDA.
 */
export type CoordinateSystem = {
    /**
     * Identifier
     */
    identifier: string;
    /**
     * Uuid
     */
    uuid: string;
};

/**
 * CountryItem
 *
 * A single country in the ``smda.masterdata.country`` list of countries
 * known to SMDA.
 */
export type CountryItem = {
    /**
     * Identifier
     */
    identifier: string;
    /**
     * Uuid
     */
    uuid: string;
};

/**
 * DataSystem
 *
 * The system or application data is being mapping to or from.
 */
export type DataSystem = 'rms' | 'smda' | 'simulator' | 'pdm';

/**
 * DiscoveryItem
 *
 * A single discovery in the ``masterdata.smda.discovery`` list of discoveries
 * known to SMDA.
 */
export type DiscoveryItem = {
    /**
     * Short Identifier
     */
    short_identifier: string;
    /**
     * Uuid
     */
    uuid: string;
};

/**
 * FMUDirPath
 *
 * Path where a .fmu directory may exist.
 */
export type FmuDirPath = {
    /**
     * Path
     *
     * Absolute path to the directory which maybe contains a .fmu directory.
     */
    path: string;
};

/**
 * FMUProject
 *
 * Information returned when 'opening' an FMU Directory.
 */
export type FmuProject = {
    /**
     * Path
     *
     * Absolute path to the directory which maybe contains a .fmu directory.
     */
    path: string;
    /**
     * Project Dir Name
     *
     * The directory name, not the path, that contains the .fmu directory.
     */
    project_dir_name: string;
    /**
     * The configuration of an FMU project's .fmu directory.
     */
    config: ProjectConfig;
};

/**
 * FieldItem
 *
 * A single field in the ``masterdata.smda.field`` list of fields
 * known to SMDA.
 */
export type FieldItem = {
    /**
     * Identifier
     */
    identifier: string;
    /**
     * Uuid
     */
    uuid: string;
};

/**
 * FilterType
 *
 * The supported types to filter on.
 */
export type FilterType = 'date' | 'number' | 'text';

/**
 * GlobalConfigPath
 *
 * A relative path to a global config file, relative to the project root.
 */
export type GlobalConfigPath = {
    /**
     * Relative Path
     *
     * Relative path in the project to a global config file.
     */
    relative_path: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InternalMappings
 *
 * Represents the .fmu/mappings.json storage schema.
 */
export type InternalMappings = {
    /**
     * Schema Version
     */
    schema_version?: 1;
    stratigraphy?: InternalStratigraphyMappings;
    wellbore?: InternalWellboreMappings;
};

/**
 * InternalRelationType
 *
 * The kind of relation this internal .fmu mapping represents.
 */
export type InternalRelationType = 'primary' | 'alias' | 'unmappable';

/**
 * InternalStratigraphyIdentifierMapping
 *
 * Stratigraphy identifier mapping stored in .fmu/mappings.json.
 *
 * Use ``to_stratigraphy_mappings()`` on the collection model when consumers
 * need the fmu-datamodels mapping schema.
 */
export type InternalStratigraphyIdentifierMapping = {
    source_system: DataSystem;
    target_system: DataSystem;
    /**
     * Mapping Type
     */
    mapping_type?: 'stratigraphy';
    relation_type: InternalRelationType;
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Source Uuid
     */
    source_uuid?: string | null;
    /**
     * Target Id
     */
    target_id?: string | null;
    /**
     * Target Uuid
     */
    target_uuid?: string | null;
};

/**
 * InternalStratigraphyMappings
 *
 * Collection of stratigraphy mappings stored in .fmu/mappings.json.
 *
 * This internal model can keep same-system alias information and unmappable
 * relation. Converting to fmu-datamodels drops unmappable entries and expands
 * same-system aliases onto matching cross-system primary mappings.
 */
export type InternalStratigraphyMappings = Array<InternalStratigraphyIdentifierMapping>;

/**
 * InternalWellboreIdentifierMapping
 *
 * Wellbore identifier mapping stored in .fmu/mappings.json.
 *
 * Use ``to_wellbore_mappings()`` on the collection model when consumers need
 * the fmu-datamodels mapping schema.
 */
export type InternalWellboreIdentifierMapping = {
    source_system: DataSystem;
    target_system: DataSystem;
    /**
     * Mapping Type
     */
    mapping_type?: 'wellbore';
    relation_type: InternalRelationType;
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Source Uuid
     */
    source_uuid?: string | null;
    /**
     * Target Id
     */
    target_id?: string | null;
    /**
     * Target Uuid
     */
    target_uuid?: string | null;
};

/**
 * InternalWellboreMappings
 *
 * Collection of wellbore mappings stored in .fmu/mappings.json.
 *
 * This internal model can keep same-system alias information and unmappable
 * relation. Converting to fmu-datamodels drops unmappable entries and expands
 * same-system aliases onto matching cross-system primary mappings.
 */
export type InternalWellboreMappings = Array<InternalWellboreIdentifierMapping>;

/**
 * ListFieldDiff
 *
 * Diff entry for list fields with per-item changes.
 */
export type ListFieldDiff = {
    /**
     * Field Path
     */
    field_path: string;
    /**
     * Added
     */
    added: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Removed
     */
    removed: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Updated
     */
    updated: Array<ListUpdatedEntry>;
};

/**
 * ListUpdatedEntry
 *
 * Before and after values for an updated list item.
 */
export type ListUpdatedEntry = {
    /**
     * Key
     */
    key: unknown;
    /**
     * Before
     */
    before: {
        [key: string]: unknown;
    };
    /**
     * After
     */
    after: {
        [key: string]: unknown;
    };
};

/**
 * LockInfo
 *
 * Represents a .fmu directory lock file.
 */
export type LockInfo = {
    /**
     * Pid
     */
    pid: number;
    /**
     * Hostname
     */
    hostname: string;
    /**
     * User
     */
    user: string;
    /**
     * Acquired At
     */
    acquired_at: number;
    /**
     * Expires At
     */
    expires_at: number;
    /**
     * Version
     */
    version?: string;
};

/**
 * LockStatus
 *
 * Information about the project lock status.
 */
export type LockStatus = {
    /**
     * Is Lock Acquired
     *
     * Whether the current session holds the write lock.
     */
    is_lock_acquired: boolean;
    /**
     * Lock File Exists
     *
     * Whether a lock file exists.
     */
    lock_file_exists: boolean;
    /**
     * Contents of the lock file, if available and readable.
     */
    lock_info?: LockInfo | null;
    /**
     * Lock Status Error
     *
     * Error message if checking lock status failed.
     */
    lock_status_error?: string | null;
    /**
     * Lock File Read Error
     *
     * Error message if reading the lock file failed.
     */
    lock_file_read_error?: string | null;
    /**
     * Last Lock Acquire Error
     *
     * Error message from the last attempt to acquire the lock.
     */
    last_lock_acquire_error?: string | null;
    /**
     * Last Lock Release Error
     *
     * Error message from the last attempt to release the lock.
     */
    last_lock_release_error?: string | null;
    /**
     * Last Lock Refresh Error
     *
     * Error message from the last attempt to refresh the lock.
     */
    last_lock_refresh_error?: string | null;
};

/**
 * Log[ChangeInfo]
 */
export type LogChangeInfo = Array<ChangeInfo>;

/**
 * MappingType
 *
 * The discriminator used between mapping types.
 *
 * Each of these types should have their own mapping class derived from a base
 * mapping type, e.g. IdentifierMapping.
 */
export type MappingType = 'stratigraphy' | 'wellbore';

/**
 * Masterdata
 *
 * The ``masterdata`` block contains information related to masterdata.
 * Currently, SMDA holds the masterdata.
 */
export type Masterdata = {
    smda: Smda;
};

/**
 * MatchCandidate
 *
 * A target candidate for a source name.
 */
export type MatchCandidate = {
    /**
     * Target
     *
     * The candidate target name.
     */
    target: string;
    /**
     * Score
     *
     * Similarity score for the normalized source and target names (0-100).
     */
    score: number;
    /**
     * Confidence
     *
     * Confidence level based on score.
     *
     * 'high' (>80), 'medium' (50-80), 'low' (<50).
     */
    confidence: 'high' | 'medium' | 'low';
};

/**
 * MatchReplacementRule
 *
 * A normalized token sequence replacement to apply before matching.
 */
export type MatchReplacementRule = {
    /**
     * Original
     *
     * The normalized token sequence to replace.
     */
    original: string;
    /**
     * Replacement
     *
     * The replacement token sequence.
     */
    replacement: string;
};

/**
 * MatchRequest
 *
 * A request to match source names against target names.
 */
export type MatchRequest = {
    /**
     * Sources
     *
     * Names to match from.
     */
    sources: Array<string>;
    /**
     * Targets
     *
     * Names to match against.
     */
    targets: Array<string>;
    /**
     * Replacements
     *
     * Optional normalized token sequence replacements to apply before matching.
     */
    replacements?: Array<MatchReplacementRule>;
};

/**
 * MatchResult
 *
 * The target candidates for a source name.
 */
export type MatchResult = {
    /**
     * Source
     *
     * The source name.
     */
    source: string;
    /**
     * Matches
     *
     * The best target candidates for the source name.
     */
    matches: Array<MatchCandidate>;
};

/**
 * Message
 *
 * A generic message to return to the GUI.
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * Model
 *
 * The ``fmu.model`` block contains information about the model used.
 *
 * .. note::
 * Synonyms for "model" in this context are "template", "setup", etc. The term
 * "model" is ultra-generic but was chosen before e.g. "template" as the latter
 * deviates from daily communications and is, if possible, even more generic
 * than "model".
 */
export type Model = {
    /**
     * Description
     */
    description?: Array<string> | null;
    /**
     * Name
     */
    name: string;
    /**
     * Revision
     */
    revision: string;
};

/**
 * Ok
 *
 * Returns "ok" if the route is functioning correctly.
 */
export type Ok = {
    /**
     * Status
     */
    status?: 'ok';
};

/**
 * ProjectConfig
 *
 * The configuration file in a .fmu directory.
 *
 * Stored as config.json.
 */
export type ProjectConfig = {
    /**
     * Schema Version
     */
    schema_version?: 1;
    /**
     * Version
     */
    version: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Last Modified At
     */
    last_modified_at?: string | null;
    /**
     * Last Modified By
     */
    last_modified_by?: string | null;
    masterdata?: Masterdata | null;
    model?: Model | null;
    access?: Access | null;
    /**
     * Cache Max Revisions
     */
    cache_max_revisions?: number;
    rms?: RmsProject | null;
    validation?: ProjectValidation;
};

/**
 * ProjectValidation
 *
 * Validation metadata for project configuration data.
 */
export type ProjectValidation = {
    masterdata_smda?: ValidationRecord | null;
    rms_project?: ValidationRecord | null;
};

/**
 * RestorableFilesResponse
 *
 * A list of missing .fmu files that can be restored or were restored.
 */
export type RestorableFilesResponse = {
    /**
     * Files
     *
     * Relative paths to the restorable or restored files.
     */
    files: Array<string>;
};

/**
 * RmsCoordinateSystem
 *
 * The project coordinate system of an RMS project.
 */
export type RmsCoordinateSystem = {
    /**
     * Name
     */
    name: string;
};

/**
 * RmsHorizon
 *
 * A horizon from an RMS project.
 */
export type RmsHorizon = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: 'calculated' | 'calculated_unconformity' | 'interpreted' | 'interpreted_unconformity' | 'interpreted_intrusion';
};

/**
 * RmsProject
 *
 * RMS project configuration.
 */
export type RmsProject = {
    /**
     * Path
     */
    path: string;
    /**
     * Version
     */
    version: string;
    coordinate_system?: RmsCoordinateSystem | null;
    /**
     * Zones
     */
    zones?: Array<RmsStratigraphicZone> | null;
    /**
     * Horizons
     */
    horizons?: Array<RmsHorizon> | null;
    /**
     * Wells
     */
    wells?: Array<RmsWell> | null;
};

/**
 * RmsProjectPath
 *
 * Path to an RMS project within the FMU project.
 */
export type RmsProjectPath = {
    /**
     * Path
     *
     * Absolute path to the RMS project within the FMU project.
     */
    path: string;
};

/**
 * RmsProjectPathsResult
 *
 * List of RMS project paths within the FMU project.
 */
export type RmsProjectPathsResult = {
    /**
     * Results
     *
     * List of absolute paths to RMS projects within the FMU project.
     */
    results: Array<RmsProjectPath>;
};

/**
 * RmsSimulatorMappingFilePath
 *
 * A path to an RMS-to-simulator mapping import or export file.
 */
export type RmsSimulatorMappingFilePath = {
    /**
     * Relative Path
     *
     * Relative path in the project to an RMS-to-simulator mapping file.
     */
    relative_path: string;
};

/**
 * RmsStratigraphicFramework
 *
 * RMS stratigraphic framework consisting of zones and horizons.
 */
export type RmsStratigraphicFramework = {
    /**
     * Zones
     *
     * List of RMS stratigraphic zones.
     */
    zones: Array<RmsStratigraphicZone>;
    /**
     * Horizons
     *
     * List of RMS horizons.
     */
    horizons: Array<RmsHorizon>;
};

/**
 * RmsStratigraphicZone
 *
 * A stratigraphic zone from an RMS project.
 */
export type RmsStratigraphicZone = {
    /**
     * Name
     */
    name: string;
    /**
     * Top Horizon Name
     */
    top_horizon_name: string;
    /**
     * Base Horizon Name
     */
    base_horizon_name: string;
    /**
     * Stratigraphic Column Name
     */
    stratigraphic_column_name?: Array<string> | null;
};

/**
 * RmsVersion
 *
 * RMS version.
 */
export type RmsVersion = {
    /**
     * Version
     *
     * A version of RMS.
     */
    version: string;
};

/**
 * RmsWell
 *
 * A well from an RMS project with added metadata.
 */
export type RmsWell = {
    /**
     * Name
     */
    name: string;
    /**
     * Planned
     */
    planned?: boolean;
};

/**
 * ScalarFieldDiff
 *
 * Diff entry for non-list fields.
 */
export type ScalarFieldDiff = {
    /**
     * Field Path
     */
    field_path: string;
    /**
     * Before
     */
    before: unknown;
    /**
     * After
     */
    after: unknown;
};

/**
 * SessionResponse
 *
 * Serializable representation of the current session.
 */
export type SessionResponse = {
    /**
     * Id
     *
     * Session identifier.
     */
    id: string;
    /**
     * Created At
     *
     * Timestamp when the session was created.
     */
    created_at: string;
    /**
     * Expires At
     *
     * Timestamp when the session will expire.
     */
    expires_at: string;
    /**
     * Rms Expires At
     *
     * Timestamp when the RMS session will expire.
     */
    rms_expires_at: string | null;
    /**
     * Last Accessed
     *
     * Timestamp when the session was last accessed.
     */
    last_accessed: string;
};

/**
 * Smda
 *
 * The ``masterdata.smda`` block contains SMDA-related attributes.
 */
export type Smda = {
    coordinate_system: CoordinateSystem;
    /**
     * Country
     */
    country: Array<CountryItem>;
    /**
     * Discovery
     */
    discovery: Array<DiscoveryItem>;
    /**
     * Field
     */
    field: Array<FieldItem>;
    stratigraphic_column: StratigraphicColumn;
};

/**
 * SmdaField
 *
 * An identifier for a field to be searched for.
 */
export type SmdaField = {
    /**
     * Identifier
     *
     * A field identifier (name).
     */
    identifier: string;
};

/**
 * SmdaFieldSearchResult
 *
 * The search result of a field identifier result.
 */
export type SmdaFieldSearchResult = {
    /**
     * Hits
     *
     * The number of hits from the field search.
     */
    hits: number;
    /**
     * Pages
     *
     * The number of pages of hits.
     */
    pages: number;
    /**
     * Results
     *
     * A list of field identifier results from the search.
     */
    results: Array<SmdaFieldUuid>;
};

/**
 * SmdaFieldUUID
 *
 * Name-UUID identifier for a field as known by SMDA.
 */
export type SmdaFieldUuid = {
    /**
     * Identifier
     *
     * A field identifier (name).
     */
    identifier: string;
    /**
     * Uuid
     *
     * The SMDA UUID identifier corresponding to the field identifier.
     */
    uuid: string;
    /**
     * Country
     *
     * The country identifier corresponding to the field identifier.
     */
    country: string;
};

/**
 * SmdaMasterdataResult
 *
 * Contains SMDA-related attributes.
 */
export type SmdaMasterdataResult = {
    /**
     * Field
     *
     * A list referring to fields known to SMDA. First item is primary.
     */
    field: Array<FieldItem>;
    /**
     * Country
     *
     * A list referring to countries known to SMDA. First item is primary.
     */
    country: Array<CountryItem>;
    /**
     * Discovery
     *
     * A list referring to discoveries known to SMDA. First item is primary.
     */
    discovery: Array<DiscoveryItem>;
    /**
     * Stratigraphic Columns
     *
     * Reference to stratigraphic column known to SMDA.
     */
    stratigraphic_columns: Array<StratigraphicColumn>;
    /**
     * The primary field's coordinate system.
     *
     * This coordinate system may not be the coordinate system users use in their model.
     */
    field_coordinate_system: CoordinateSystem;
    /**
     * Coordinate Systems
     *
     * A list of all coordinate systems known to SMDA.
     *
     * These are provided when the user needs to select a different coordinate system that
     * applies to the model they are working on.
     */
    coordinate_systems: Array<CoordinateSystem>;
};

/**
 * SmdaSelectedField
 *
 * A selected field for masterdata lookup.
 */
export type SmdaSelectedField = {
    /**
     * Identifier
     *
     * A field identifier (name).
     */
    identifier: string;
    /**
     * Uuid
     *
     * The SMDA UUID identifier corresponding to the field identifier.
     */
    uuid?: string | null;
};

/**
 * SmdaStratColumn
 *
 * An identifier for a stratigraphic column.
 */
export type SmdaStratColumn = {
    /**
     * Strat Column Identifier
     *
     * A stratigraphic column identifier.
     */
    strat_column_identifier: string;
};

/**
 * SmdaStratigraphicUnitsResult
 *
 * Result containing a list of stratigraphic units.
 */
export type SmdaStratigraphicUnitsResult = {
    /**
     * Stratigraphic Units
     *
     * List of stratigraphic units from SMDA.
     */
    stratigraphic_units: Array<StratigraphicUnit>;
};

/**
 * SmdaWellHeader
 *
 * Well header data from SMDA.
 */
export type SmdaWellHeader = {
    /**
     * Unique Well Identifier
     *
     * Unique SMDA identifier for the well.
     */
    unique_well_identifier: string;
    /**
     * Unique Wellbore Identifier
     *
     * Unique SMDA identifier for the wellbore.
     */
    unique_wellbore_identifier: string;
    /**
     * Official Wellbore Name
     *
     * Official wellbore name used by the Authorities.
     *
     * For Norway and UK, it will be the unique_wellbore_identifier without
     * country iso code, but for Brazil it can really differs from the Equinor
     * wellbore name.
     */
    official_wellbore_name: string | null;
    /**
     * Country Identifier
     *
     * Country identifier for the wellbore.
     */
    country_identifier: string;
    /**
     * Parent Wellbore
     *
     * The unique wellbore identifier this wellbore is kicked off from.
     *
     * Ref. kick off depth. This is used for sidetracks. A wellbore starting at
     * the well origin has no parent.
     */
    parent_wellbore: string | null;
    /**
     * Wellbore Type
     *
     * Type of wellbore, values like exploration, development, other.
     *
     * This attribute is automatically maintained in SMDA based on the wellbore
     * purpose. If the purpose is like wildcat or appraisal, type will be set to
     * exploration, if the purpose is like production, injection then the type is
     * set to development.
     */
    wellbore_type: string | null;
    /**
     * Wellbore Purpose
     *
     * Purpose of wellbore.
     *
     * Values like wildcat, appraisal, … for exploration wellbores; production,
     * injection, observation, disposal, … for development wellbores; shallow gas,
     * pilot hole for other purpose.
     */
    wellbore_purpose: string | null;
    /**
     * Wellbore Status
     *
     * Status of the wellbore.
     *
     * Value like plugged and abandoned, drilling, plugged, producing ... This
     * attribute is automatically maintained in SMDA if no good source is found
     * for it. SMDA will use the wellbore type (exploration or development), the
     * drill dates information, current_track, etc ... in order to set a plausible
     * status. If wellbore type=exploration and completed_date < current_date,
     * then status=plugged and abandoned while development wellbore would be set
     * to completed.
     */
    wellbore_status: string | null;
    /**
     * Wellbore Purpose Planned
     *
     * Pre-drill purpose of the wellbore.
     *
     * Legal values for exploration wellbores: wildcat, appraisal. Example of
     * legal values for development wellbores: observation, production, injection.
     */
    wellbore_purpose_planned: string | null;
    /**
     * Drill Year
     *
     * The year when the drilling has started.
     */
    drill_year: number | null;
    /**
     * Completion Date
     *
     * Date when the wellbore is considered completed.
     *
     * For exploration wellbores from moveable facilities, this may be the anchor
     * handling or jacking-down start date. For fixed facilities and development
     * wellbores, it is when the wellbore reaches total depth and the last casing,
     * liner, or screen is set. If immediately plugged, it is the date the last
     * plug is set.
     */
    completion_date: string | null;
    /**
     * Discovery Internal Identifier
     *
     * Internal name of the discovery.
     */
    discovery_internal_identifier: string | null;
    /**
     * Multilateral
     *
     * Whether the wellbore is multilateral. 0 = no, 1 = yes.
     */
    multilateral: 0 | 1 | null;
    /**
     * Projected Coordinate Unit
     *
     * Projected coordinate unit.
     */
    projected_coordinate_unit: string | null;
    /**
     * Projected Coordinate System
     *
     * Coordinate reference system for the easting/northing values.
     */
    projected_coordinate_system: string | null;
    /**
     * Well Uuid
     *
     * SMDA UUID for the well.
     */
    well_uuid: string;
    /**
     * Wellbore Uuid
     *
     * SMDA UUID for the wellbore.
     */
    wellbore_uuid: string;
};

/**
 * SmdaWellHeadersResult
 *
 * Result containing a list of well headers.
 */
export type SmdaWellHeadersResult = {
    /**
     * Well Headers
     *
     * List of well headers from SMDA.
     */
    well_headers: Array<SmdaWellHeader>;
};

/**
 * StratigraphicColumn
 *
 * The ``masterdata.smda.stratigraphic_column`` block contains the
 * stratigraphic column known to SMDA.
 */
export type StratigraphicColumn = {
    /**
     * Identifier
     */
    identifier: string;
    /**
     * Uuid
     */
    uuid: string;
};

/**
 * StratigraphicUnit
 *
 * Stratigraphic unit item.
 */
export type StratigraphicUnit = {
    /**
     * Identifier
     *
     * The stratigraphic unit identifier (name).
     */
    identifier: string;
    /**
     * Uuid
     *
     * The SMDA UUID identifier corresponding to the stratigraphic unit.
     */
    uuid: string;
    /**
     * Strat Unit Type
     *
     * The type of stratigraphic unit.
     */
    strat_unit_type: string;
    /**
     * Strat Unit Level
     *
     * The hierarchical level of the stratigraphic unit (1-6).
     */
    strat_unit_level: number;
    /**
     * Top
     *
     * The identifier (name) of the stratigraphic unit top pick (horizon).
     */
    top: string;
    /**
     * Top Uuid
     *
     * The SMDA UUID identifier corresponding to the top horizon.
     */
    top_uuid: string | null;
    /**
     * Base
     *
     * The identifier (name) of the stratigraphic unit base pick (horizon).
     */
    base: string;
    /**
     * Base Uuid
     *
     * The SMDA UUID identifier corresponding to the base horizon.
     */
    base_uuid: string | null;
    /**
     * Top Age
     *
     * The age (in Ma) at the top of the stratigraphic unit.
     */
    top_age: number;
    /**
     * Base Age
     *
     * The age (in Ma) at the base of the stratigraphic unit.
     */
    base_age: number;
    /**
     * Strat Unit Parent
     *
     * The parent stratigraphic unit identifier, if applicable.
     */
    strat_unit_parent: string | null;
    /**
     * Strat Column Type
     *
     * The type of stratigraphic column this unit belongs to.
     */
    strat_column_type: 'lithostratigraphy' | 'sequence stratigraphy' | 'chronostratigraphy' | 'biostratigraphy';
    /**
     * Color Html
     *
     * The HTML hex color code for visualization.
     */
    color_html?: string | null;
    /**
     * Color R
     *
     * The red component of the RGB color.
     */
    color_r: number | null;
    /**
     * Color G
     *
     * The green component of the RGB color.
     */
    color_g: number | null;
    /**
     * Color B
     *
     * The blue component of the RGB color.
     */
    color_b: number | null;
};

/**
 * SumoAsset
 *
 * A valid asset in Sumo.
 */
export type SumoAsset = {
    /**
     * Name
     *
     * Name of the asset in Sumo.
     */
    name: string;
    /**
     * Code
     *
     * Code of the asset in Sumo.
     */
    code: string;
    /**
     * Roleprefix
     *
     * Roleprefix of the asset in Sumo.
     */
    roleprefix: string;
};

/**
 * UserAPIKeys
 *
 * Known API keys stored in a user config.
 */
export type UserApiKeys = {
    /**
     * Smda Subscription
     */
    smda_subscription?: string | null;
};

/**
 * UserConfig
 *
 * The configuration file in a $HOME/.fmu directory.
 *
 * Stored as config.json.
 */
export type UserConfig = {
    /**
     * Schema Version
     */
    schema_version?: 1;
    /**
     * Version
     */
    version: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Last Modified At
     */
    last_modified_at?: string | null;
    /**
     * Cache Max Revisions
     */
    cache_max_revisions?: number;
    user_api_keys: UserApiKeys;
    /**
     * Recent Project Directories
     */
    recent_project_directories: Array<string>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ValidationRecord
 *
 * Metadata for a successful validation of project configuration data.
 */
export type ValidationRecord = {
    /**
     * Last Validated At
     */
    last_validated_at: string;
    /**
     * Last Validated By
     */
    last_validated_by: string;
};

/**
 * APIKey
 *
 * A key-value pair for a known and supported API.
 */
export type ApiKeyWritable = {
    /**
     * Id
     */
    id: string;
    /**
     * Key
     */
    key: string;
};

/**
 * AccessToken
 *
 * A key-value pair for a known and supported access scope.
 */
export type AccessTokenWritable = {
    /**
     * Id
     */
    id: string;
    /**
     * Key
     */
    key: string;
};

export type ProjectDeleteProjectSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project/';
};

export type ProjectDeleteProjectSessionErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectDeleteProjectSessionError = ProjectDeleteProjectSessionErrors[keyof ProjectDeleteProjectSessionErrors];

export type ProjectDeleteProjectSessionResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectDeleteProjectSessionResponse = ProjectDeleteProjectSessionResponses[keyof ProjectDeleteProjectSessionResponses];

export type ProjectGetProjectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project/';
};

export type ProjectGetProjectErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectGetProjectError = ProjectGetProjectErrors[keyof ProjectGetProjectErrors];

export type ProjectGetProjectResponses = {
    /**
     * Successful Response
     */
    200: FmuProject;
};

export type ProjectGetProjectResponse = ProjectGetProjectResponses[keyof ProjectGetProjectResponses];

export type ProjectPostProjectData = {
    body: FmuDirPath;
    path?: never;
    query?: never;
    url: '/api/v1/project/';
};

export type ProjectPostProjectErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     *
     * A project .fmu directory already exist at a given location, or may
     * possibly not be a directory, i.e. it may be a .fmu file.
     *
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPostProjectError = ProjectPostProjectErrors[keyof ProjectPostProjectErrors];

export type ProjectPostProjectResponses = {
    /**
     * Successful Response
     */
    200: FmuProject;
};

export type ProjectPostProjectResponse = ProjectPostProjectResponses[keyof ProjectPostProjectResponses];

export type ProjectGetSumoAssetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project/sumo_assets';
};

export type ProjectGetSumoAssetsErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Sumo assets file not found
     */
    404: unknown;
    /**
     * Invalid file content in Sumo assets file
     */
    422: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectGetSumoAssetsResponses = {
    /**
     * Response Project-Get Sumo Assets
     *
     * Successful Response
     */
    200: Array<SumoAsset>;
};

export type ProjectGetSumoAssetsResponse = ProjectGetSumoAssetsResponses[keyof ProjectGetSumoAssetsResponses];

export type ProjectGetGlobalConfigStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project/global_config_status';
};

export type ProjectGetGlobalConfigStatusErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     *
     * The global config file was not found at a given location.
     *
     */
    404: unknown;
    /**
     *
     * The project .fmu config already contains masterdata.
     *
     */
    409: unknown;
    /**
     *
     * The global config file did not validate against the
     * GlobalConfiguration Pydantic model.
     *
     */
    422: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectGetGlobalConfigStatusResponses = {
    /**
     * Successful Response
     */
    200: Ok;
};

export type ProjectGetGlobalConfigStatusResponse = ProjectGetGlobalConfigStatusResponses[keyof ProjectGetGlobalConfigStatusResponses];

export type ProjectPostInitProjectData = {
    body: FmuDirPath;
    path?: never;
    query?: never;
    url: '/api/v1/project/init';
};

export type ProjectPostInitProjectErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     *
     * A project .fmu directory already exist at a given location, or may
     * possibly not be a directory, i.e. it may be a .fmu file.
     *
     */
    409: unknown;
    /**
     * The requested path exists but is not a valid FMU project root.
     */
    422: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPostInitProjectResponses = {
    /**
     * Successful Response
     */
    200: FmuProject;
};

export type ProjectPostInitProjectResponse = ProjectPostInitProjectResponses[keyof ProjectPostInitProjectResponses];

export type ProjectPostGlobalConfigData = {
    /**
     * Path
     */
    body?: GlobalConfigPath | null;
    path?: never;
    query?: never;
    url: '/api/v1/project/global_config';
};

export type ProjectPostGlobalConfigErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     *
     * The global config file was not found at a given location.
     *
     */
    404: unknown;
    /**
     *
     * The project .fmu config already contains masterdata.
     *
     */
    409: unknown;
    /**
     *
     * The global config file did not validate against the
     * GlobalConfiguration Pydantic model.
     *
     */
    422: unknown;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPostGlobalConfigResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPostGlobalConfigResponse = ProjectPostGlobalConfigResponses[keyof ProjectPostGlobalConfigResponses];

export type ProjectPostLockAcquireData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project/lock_acquire';
};

export type ProjectPostLockAcquireErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPostLockAcquireError = ProjectPostLockAcquireErrors[keyof ProjectPostLockAcquireErrors];

export type ProjectPostLockAcquireResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPostLockAcquireResponse = ProjectPostLockAcquireResponses[keyof ProjectPostLockAcquireResponses];

export type ProjectPostLockReleaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project/lock_release';
};

export type ProjectPostLockReleaseErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPostLockReleaseError = ProjectPostLockReleaseErrors[keyof ProjectPostLockReleaseErrors];

export type ProjectPostLockReleaseResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPostLockReleaseResponse = ProjectPostLockReleaseResponses[keyof ProjectPostLockReleaseResponses];

export type ProjectPostLockRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project/lock_refresh';
};

export type ProjectPostLockRefreshErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPostLockRefreshError = ProjectPostLockRefreshErrors[keyof ProjectPostLockRefreshErrors];

export type ProjectPostLockRefreshResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPostLockRefreshResponse = ProjectPostLockRefreshResponses[keyof ProjectPostLockRefreshResponses];

export type ProjectGetLockStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project/lock_status';
};

export type ProjectGetLockStatusErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectGetLockStatusError = ProjectGetLockStatusErrors[keyof ProjectGetLockStatusErrors];

export type ProjectGetLockStatusResponses = {
    /**
     * Successful Response
     */
    200: LockStatus;
};

export type ProjectGetLockStatusResponse = ProjectGetLockStatusResponses[keyof ProjectGetLockStatusResponses];

export type ProjectPatchMasterdataData = {
    body: Smda;
    path?: never;
    query?: never;
    url: '/api/v1/project/masterdata';
};

export type ProjectPatchMasterdataErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPatchMasterdataError = ProjectPatchMasterdataErrors[keyof ProjectPatchMasterdataErrors];

export type ProjectPatchMasterdataResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPatchMasterdataResponse = ProjectPatchMasterdataResponses[keyof ProjectPatchMasterdataResponses];

export type ProjectPostValidateMasterdataSmdaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project/validate/masterdata/smda';
};

export type ProjectPostValidateMasterdataSmdaErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Project masterdata is missing or does not match SMDA
     */
    422: unknown;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * SMDA returns a malformed response
     */
    500: unknown;
    /**
     * An API call to SMDA times out or fails
     */
    503: unknown;
};

export type ProjectPostValidateMasterdataSmdaResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPostValidateMasterdataSmdaResponse = ProjectPostValidateMasterdataSmdaResponses[keyof ProjectPostValidateMasterdataSmdaResponses];

export type ProjectPatchModelData = {
    body: Model;
    path?: never;
    query?: never;
    url: '/api/v1/project/model';
};

export type ProjectPatchModelErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPatchModelError = ProjectPatchModelErrors[keyof ProjectPatchModelErrors];

export type ProjectPatchModelResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPatchModelResponse = ProjectPatchModelResponses[keyof ProjectPatchModelResponses];

export type ProjectPatchAccessData = {
    body: Access;
    path?: never;
    query?: never;
    url: '/api/v1/project/access';
};

export type ProjectPatchAccessErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPatchAccessError = ProjectPatchAccessErrors[keyof ProjectPatchAccessErrors];

export type ProjectPatchAccessResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPatchAccessResponse = ProjectPatchAccessResponses[keyof ProjectPatchAccessResponses];

export type ProjectPatchCacheMaxRevisionsData = {
    body: CacheRetention;
    path?: never;
    query?: never;
    url: '/api/v1/project/cache_max_revisions';
};

export type ProjectPatchCacheMaxRevisionsErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPatchCacheMaxRevisionsError = ProjectPatchCacheMaxRevisionsErrors[keyof ProjectPatchCacheMaxRevisionsErrors];

export type ProjectPatchCacheMaxRevisionsResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPatchCacheMaxRevisionsResponse = ProjectPatchCacheMaxRevisionsResponses[keyof ProjectPatchCacheMaxRevisionsResponses];

export type ProjectGetRmsProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project/rms_projects';
};

export type ProjectGetRmsProjectsErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectGetRmsProjectsError = ProjectGetRmsProjectsErrors[keyof ProjectGetRmsProjectsErrors];

export type ProjectGetRmsProjectsResponses = {
    /**
     * Successful Response
     */
    200: RmsProjectPathsResult;
};

export type ProjectGetRmsProjectsResponse = ProjectGetRmsProjectsResponses[keyof ProjectGetRmsProjectsResponses];

export type ProjectPatchRmsData = {
    body: RmsProjectPath;
    path?: never;
    query?: never;
    url: '/api/v1/project/rms';
};

export type ProjectPatchRmsErrors = {
    /**
     * The RMS version in the project is not supported
     */
    400: unknown;
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPatchRmsError = ProjectPatchRmsErrors[keyof ProjectPatchRmsErrors];

export type ProjectPatchRmsResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPatchRmsResponse = ProjectPatchRmsResponses[keyof ProjectPatchRmsResponses];

export type ProjectPatchRmsCoordinateSystemData = {
    body: RmsCoordinateSystem;
    path?: never;
    query?: never;
    url: '/api/v1/project/rms/coordinate_system';
};

export type ProjectPatchRmsCoordinateSystemErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     *
     * RMS project path must be set before updating RMS fields.
     *
     */
    422: unknown;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPatchRmsCoordinateSystemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPatchRmsCoordinateSystemResponse = ProjectPatchRmsCoordinateSystemResponses[keyof ProjectPatchRmsCoordinateSystemResponses];

export type ProjectPatchRmsStratigraphicFrameworkData = {
    body: RmsStratigraphicFramework;
    path?: never;
    query?: never;
    url: '/api/v1/project/rms/stratigraphic_framework';
};

export type ProjectPatchRmsStratigraphicFrameworkErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     *
     * The RMS stratigraphic framework did not validate.
     *
     */
    422: unknown;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPatchRmsStratigraphicFrameworkResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPatchRmsStratigraphicFrameworkResponse = ProjectPatchRmsStratigraphicFrameworkResponses[keyof ProjectPatchRmsStratigraphicFrameworkResponses];

export type ProjectPatchRmsWellsData = {
    /**
     * Wells
     */
    body: Array<RmsWell>;
    path?: never;
    query?: never;
    url: '/api/v1/project/rms/wells';
};

export type ProjectPatchRmsWellsErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     *
     * RMS project path must be set before updating RMS fields.
     *
     */
    422: unknown;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPatchRmsWellsResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPatchRmsWellsResponse = ProjectPatchRmsWellsResponses[keyof ProjectPatchRmsWellsResponses];

export type ProjectGetCacheData = {
    body?: never;
    path?: never;
    query: {
        resource: CacheResource;
    };
    url: '/api/v1/project/cache';
};

export type ProjectGetCacheErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectGetCacheError = ProjectGetCacheErrors[keyof ProjectGetCacheErrors];

export type ProjectGetCacheResponses = {
    /**
     * Successful Response
     */
    200: CacheList;
};

export type ProjectGetCacheResponse = ProjectGetCacheResponses[keyof ProjectGetCacheResponses];

export type ProjectGetCacheRevisionData = {
    body?: never;
    path: {
        /**
         * Revision Id
         */
        revision_id: string;
    };
    query: {
        resource: CacheResource;
    };
    url: '/api/v1/project/cache/{revision_id}';
};

export type ProjectGetCacheRevisionErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     * Cache revision not found for the specified resource
     */
    404: unknown;
    /**
     * Cache revision failed validation or not supported for the specified resource
     */
    422: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectGetCacheRevisionResponses = {
    /**
     * Successful Response
     */
    200: CacheContent;
};

export type ProjectGetCacheRevisionResponse = ProjectGetCacheRevisionResponses[keyof ProjectGetCacheRevisionResponses];

export type ProjectGetCacheDiffData = {
    body?: never;
    path: {
        /**
         * Revision Id
         */
        revision_id: string;
    };
    query: {
        resource: CacheResource;
    };
    url: '/api/v1/project/cache/diff/{revision_id}';
};

export type ProjectGetCacheDiffErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     * Cache revision not found for the specified resource
     */
    404: unknown;
    /**
     * Cache revision failed validation or not supported for the specified resource
     */
    422: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectGetCacheDiffResponses = {
    /**
     * Response Project-Get Cache Diff
     *
     * Successful Response
     */
    200: Array<ScalarFieldDiff | ListFieldDiff>;
};

export type ProjectGetCacheDiffResponse = ProjectGetCacheDiffResponses[keyof ProjectGetCacheDiffResponses];

export type ProjectPostCacheRestoreData = {
    body?: never;
    path: {
        /**
         * Revision Id
         */
        revision_id: string;
    };
    query: {
        resource: CacheResource;
    };
    url: '/api/v1/project/cache/restore/{revision_id}';
};

export type ProjectPostCacheRestoreErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     * Cache revision not found for the specified resource
     */
    404: unknown;
    /**
     * Cache revision failed validation or not supported for the specified resource
     */
    422: unknown;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPostCacheRestoreResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPostCacheRestoreResponse = ProjectPostCacheRestoreResponses[keyof ProjectPostCacheRestoreResponses];

export type ProjectGetRestoreCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project/restore/check';
};

export type ProjectGetRestoreCheckErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectGetRestoreCheckError = ProjectGetRestoreCheckErrors[keyof ProjectGetRestoreCheckErrors];

export type ProjectGetRestoreCheckResponses = {
    /**
     * Successful Response
     */
    200: RestorableFilesResponse;
};

export type ProjectGetRestoreCheckResponse = ProjectGetRestoreCheckResponses[keyof ProjectGetRestoreCheckResponses];

export type ProjectPostRestoreData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/project/restore';
};

export type ProjectPostRestoreErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPostRestoreError = ProjectPostRestoreErrors[keyof ProjectPostRestoreErrors];

export type ProjectPostRestoreResponses = {
    /**
     * Successful Response
     */
    200: RestorableFilesResponse;
};

export type ProjectPostRestoreResponse = ProjectPostRestoreResponses[keyof ProjectPostRestoreResponses];

export type ProjectGetMappingsData = {
    body?: never;
    path: {
        mapping_type: MappingType;
        source_system: DataSystem;
    };
    query?: never;
    url: '/api/v1/project/mappings/{mapping_type}/{source_system}';
};

export type ProjectGetMappingsErrors = {
    /**
     * Invalid mapping data or unsupported mapping type
     */
    400: unknown;
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     *
     * Mappings resource contains invalid content or corrupted JSON.
     *
     */
    422: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectGetMappingsResponses = {
    /**
     * Mappings for the requested mapping type.
     */
    200: InternalMappings;
};

export type ProjectGetMappingsResponse = ProjectGetMappingsResponses[keyof ProjectGetMappingsResponses];

export type ProjectPutMappingsData = {
    body: InternalStratigraphyMappings | InternalWellboreMappings;
    path: {
        mapping_type: MappingType;
        source_system: DataSystem;
    };
    query?: never;
    url: '/api/v1/project/mappings/{mapping_type}/{source_system}';
};

export type ProjectPutMappingsErrors = {
    /**
     * Invalid mapping data or unsupported mapping type
     */
    400: unknown;
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     * Project mappings could not be updated because the project path was missing
     */
    404: unknown;
    /**
     *
     * Mappings resource contains invalid content or corrupted JSON.
     *
     */
    422: unknown;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPutMappingsResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPutMappingsResponse = ProjectPutMappingsResponses[keyof ProjectPutMappingsResponses];

export type ProjectPostMappingsImportRmsEclipseCsvData = {
    /**
     * Path
     */
    body?: RmsSimulatorMappingFilePath | null;
    path?: never;
    query?: never;
    url: '/api/v1/project/mappings/import/rms_eclipse_csv';
};

export type ProjectPostMappingsImportRmsEclipseCsvErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The RMS-to-simulator wellbore mapping file could not be read or written
     */
    403: unknown;
    /**
     * The RMS-to-simulator wellbore mapping file could not be found
     */
    404: unknown;
    /**
     *
     * The RMS-to-simulator wellbore mapping file contains invalid content,
     * or no mappings can be exported.
     *
     */
    422: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPostMappingsImportRmsEclipseCsvResponses = {
    /**
     * Successful Response
     */
    200: InternalMappings;
};

export type ProjectPostMappingsImportRmsEclipseCsvResponse = ProjectPostMappingsImportRmsEclipseCsvResponses[keyof ProjectPostMappingsImportRmsEclipseCsvResponses];

export type ProjectPostMappingsExportRmsSimulatorRenamingTableData = {
    /**
     * Path
     */
    body?: RmsSimulatorMappingFilePath | null;
    path?: never;
    query?: never;
    url: '/api/v1/project/mappings/export/rms_simulator_renaming_table';
};

export type ProjectPostMappingsExportRmsSimulatorRenamingTableErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The RMS-to-simulator wellbore mapping file could not be read or written
     */
    403: unknown;
    /**
     * The RMS-to-simulator wellbore mapping file could not be found
     */
    404: unknown;
    /**
     *
     * The RMS-to-simulator wellbore mapping file contains invalid content,
     * or no mappings can be exported.
     *
     */
    422: unknown;
    /**
     *
     * The project is locked by another process and cannot be modified.
     * The project can still be read but write operations are blocked.
     *
     */
    423: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectPostMappingsExportRmsSimulatorRenamingTableResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ProjectPostMappingsExportRmsSimulatorRenamingTableResponse = ProjectPostMappingsExportRmsSimulatorRenamingTableResponses[keyof ProjectPostMappingsExportRmsSimulatorRenamingTableResponses];

export type ProjectGetChangelogData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Change Type
         */
        change_type?: ChangeType | null;
        /**
         * Max Entries
         */
        max_entries?: number | null;
        /**
         * Field Name
         */
        field_name?: string | null;
        /**
         * Filter Value
         */
        filter_value?: string | null;
        /**
         * Filter Type
         */
        filter_type?: FilterType | null;
        /**
         * Operator
         */
        operator?: '>' | '>=' | '<' | '<=' | '==' | '!=' | null;
    };
    url: '/api/v1/project/changelog';
};

export type ProjectGetChangelogErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     * Changelog file not found
     */
    404: unknown;
    /**
     * Invalid changelog data or query parameters
     */
    422: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type ProjectGetChangelogResponses = {
    /**
     * Successful Response
     */
    200: LogChangeInfo;
};

export type ProjectGetChangelogResponse = ProjectGetChangelogResponses[keyof ProjectGetChangelogResponses];

export type UserGetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/';
};

export type UserGetUserErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type UserGetUserError = UserGetUserErrors[keyof UserGetUserErrors];

export type UserGetUserResponses = {
    /**
     * Successful Response
     */
    200: UserConfig;
};

export type UserGetUserResponse = UserGetUserResponses[keyof UserGetUserResponses];

export type UserPatchApiKeyData = {
    body: ApiKeyWritable;
    path?: never;
    query?: never;
    url: '/api/v1/user/api_key';
};

export type UserPatchApiKeyErrors = {
    /**
     *
     * Occurs when trying to save a key to an unknown API. An API is unknown
     * if it is not a predefined field in the fmu-settings UserAPIKeys model.
     *
     */
    400: unknown;
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * The OS returned a permissions error while locating or creating .fmu
     */
    403: unknown;
    /**
     *
     * The .fmu directory was unable to be found at or above a given path, or
     * the requested path to create a project .fmu directory at does not exist.
     *
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type UserPatchApiKeyError = UserPatchApiKeyErrors[keyof UserPatchApiKeyErrors];

export type UserPatchApiKeyResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UserPatchApiKeyResponse = UserPatchApiKeyResponses[keyof UserPatchApiKeyResponses];

export type SessionGetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/session/';
};

export type SessionGetSessionErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type SessionGetSessionError = SessionGetSessionErrors[keyof SessionGetSessionErrors];

export type SessionGetSessionResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type SessionGetSessionResponse = SessionGetSessionResponses[keyof SessionGetSessionResponses];

export type SessionPostSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/session/';
};

export type SessionPostSessionErrors = {
    /**
     *
     * Occurs when no token or an invalid token is or is not provided
     * with the x-fmu-settings-api header.
     *
     */
    401: unknown;
    /**
     *
     * Will occur if the operating system claims the user does not have
     * permission to create $HOME/.fmu. If returned something very wrong
     * is happening.
     *
     */
    403: unknown;
    /**
     *
     * Occurs when trying to create a user .fmu directory, but it already
     * exists. Typically means that .fmu exists as a file.
     *
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type SessionPostSessionError = SessionPostSessionErrors[keyof SessionPostSessionErrors];

export type SessionPostSessionResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type SessionPostSessionResponse = SessionPostSessionResponses[keyof SessionPostSessionResponses];

export type SessionPatchAccessTokenData = {
    body: AccessTokenWritable;
    path?: never;
    query?: never;
    url: '/api/v1/session/access_token';
};

export type SessionPatchAccessTokenErrors = {
    /**
     *
     * Occurs when trying to save a key to an unknown access scope. An
     * access scope/token is unknown if it is not a predefined field in the
     * the session manager's 'AccessTokens' model.
     *
     */
    400: unknown;
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type SessionPatchAccessTokenError = SessionPatchAccessTokenErrors[keyof SessionPatchAccessTokenErrors];

export type SessionPatchAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type SessionPatchAccessTokenResponse = SessionPatchAccessTokenResponses[keyof SessionPatchAccessTokenResponses];

export type SessionGetRestoreCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/session/restore/check';
};

export type SessionGetRestoreCheckErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type SessionGetRestoreCheckError = SessionGetRestoreCheckErrors[keyof SessionGetRestoreCheckErrors];

export type SessionGetRestoreCheckResponses = {
    /**
     * Successful Response
     */
    200: RestorableFilesResponse;
};

export type SessionGetRestoreCheckResponse = SessionGetRestoreCheckResponses[keyof SessionGetRestoreCheckResponses];

export type SessionPostRestoreData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/session/restore';
};

export type SessionPostRestoreErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Permission denied while restoring a .fmu directory
     */
    403: unknown;
    /**
     * A .fmu path exists but is not a directory
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type SessionPostRestoreError = SessionPostRestoreErrors[keyof SessionPostRestoreErrors];

export type SessionPostRestoreResponses = {
    /**
     * Successful Response
     */
    200: RestorableFilesResponse;
};

export type SessionPostRestoreResponse = SessionPostRestoreResponses[keyof SessionPostRestoreResponses];

export type RmsDeleteRmsProjectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/rms/';
};

export type RmsDeleteRmsProjectErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type RmsDeleteRmsProjectError = RmsDeleteRmsProjectErrors[keyof RmsDeleteRmsProjectErrors];

export type RmsDeleteRmsProjectResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type RmsDeleteRmsProjectResponse = RmsDeleteRmsProjectResponses[keyof RmsDeleteRmsProjectResponses];

export type RmsPostRmsProjectData = {
    /**
     * Rms Version
     */
    body?: RmsVersion | null;
    path?: never;
    query?: never;
    url: '/api/v1/rms/';
};

export type RmsPostRmsProjectErrors = {
    /**
     * RMS project path is not configured in the project config file.
     */
    400: unknown;
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * RMS project was not found or its version could not be determined.
     */
    404: unknown;
    /**
     * Failed to open RMS project {rms_project_path}.
     */
    422: unknown;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type RmsPostRmsProjectResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type RmsPostRmsProjectResponse = RmsPostRmsProjectResponses[keyof RmsPostRmsProjectResponses];

export type RmsGetZonesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/rms/zones';
};

export type RmsGetZonesErrors = {
    /**
     *
     * RMS project path is not configured in the project config file,
     * or no RMS project is currently open in the session.
     *
     */
    400: unknown;
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type RmsGetZonesError = RmsGetZonesErrors[keyof RmsGetZonesErrors];

export type RmsGetZonesResponses = {
    /**
     * Response Rms-Get Zones
     *
     * Successful Response
     */
    200: Array<RmsStratigraphicZone>;
};

export type RmsGetZonesResponse = RmsGetZonesResponses[keyof RmsGetZonesResponses];

export type RmsGetHorizonsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/rms/horizons';
};

export type RmsGetHorizonsErrors = {
    /**
     *
     * RMS project path is not configured in the project config file,
     * or no RMS project is currently open in the session.
     *
     */
    400: unknown;
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type RmsGetHorizonsError = RmsGetHorizonsErrors[keyof RmsGetHorizonsErrors];

export type RmsGetHorizonsResponses = {
    /**
     * Response Rms-Get Horizons
     *
     * Successful Response
     */
    200: Array<RmsHorizon>;
};

export type RmsGetHorizonsResponse = RmsGetHorizonsResponses[keyof RmsGetHorizonsResponses];

export type RmsGetWellsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/rms/wells';
};

export type RmsGetWellsErrors = {
    /**
     *
     * RMS project path is not configured in the project config file,
     * or no RMS project is currently open in the session.
     *
     */
    400: unknown;
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type RmsGetWellsError = RmsGetWellsErrors[keyof RmsGetWellsErrors];

export type RmsGetWellsResponses = {
    /**
     * Response Rms-Get Wells
     *
     * Successful Response
     */
    200: Array<RmsWell>;
};

export type RmsGetWellsResponse = RmsGetWellsResponses[keyof RmsGetWellsResponses];

export type RmsGetCoordinateSystemData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/rms/coordinate_system';
};

export type RmsGetCoordinateSystemErrors = {
    /**
     *
     * RMS project path is not configured in the project config file,
     * or no RMS project is currently open in the session.
     *
     */
    400: unknown;
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type RmsGetCoordinateSystemError = RmsGetCoordinateSystemErrors[keyof RmsGetCoordinateSystemErrors];

export type RmsGetCoordinateSystemResponses = {
    /**
     * Successful Response
     */
    200: RmsCoordinateSystem;
};

export type RmsGetCoordinateSystemResponse = RmsGetCoordinateSystemResponses[keyof RmsGetCoordinateSystemResponses];

export type SmdaGetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/smda/health';
};

export type SmdaGetHealthErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
    /**
     * SMDA API is unreachable or returns an error
     */
    503: unknown;
};

export type SmdaGetHealthError = SmdaGetHealthErrors[keyof SmdaGetHealthErrors];

export type SmdaGetHealthResponses = {
    /**
     * Successful Response
     */
    200: Ok;
};

export type SmdaGetHealthResponse = SmdaGetHealthResponses[keyof SmdaGetHealthResponses];

export type SmdaPostFieldData = {
    body: SmdaField;
    path?: never;
    query?: never;
    url: '/api/v1/smda/field';
};

export type SmdaPostFieldErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * SMDA returns a malformed response
     */
    500: unknown;
    /**
     * An API call to SMDA times out or fails
     */
    503: unknown;
};

export type SmdaPostFieldError = SmdaPostFieldErrors[keyof SmdaPostFieldErrors];

export type SmdaPostFieldResponses = {
    /**
     * Successful Response
     */
    200: SmdaFieldSearchResult;
};

export type SmdaPostFieldResponse = SmdaPostFieldResponses[keyof SmdaPostFieldResponses];

export type SmdaPostMasterdataData = {
    /**
     * Smda Fields
     */
    body: Array<SmdaSelectedField>;
    path?: never;
    query?: never;
    url: '/api/v1/smda/masterdata';
};

export type SmdaPostMasterdataErrors = {
    /**
     * Invalid parameters are provided to SMDA API
     */
    400: unknown;
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * A requested resource is not found in SMDA
     */
    404: unknown;
    /**
     *
     * SMDA returns valid data but it doesn't meet expected criteria,
     * or no results are found for a valid query.
     *
     */
    422: unknown;
    /**
     *
     * SMDA returns a malformed response that doesn't match
     * the expected structure.
     *
     */
    500: unknown;
    /**
     *
     * An API call to SMDA times out or the service is unavailable.
     *
     */
    503: unknown;
};

export type SmdaPostMasterdataResponses = {
    /**
     * Successful Response
     */
    200: SmdaMasterdataResult;
};

export type SmdaPostMasterdataResponse = SmdaPostMasterdataResponses[keyof SmdaPostMasterdataResponses];

export type SmdaPostStratUnitsData = {
    body: SmdaStratColumn;
    path?: never;
    query?: never;
    url: '/api/v1/smda/strat_units';
};

export type SmdaPostStratUnitsErrors = {
    /**
     * Invalid parameters are provided to SMDA API
     */
    400: unknown;
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * A requested resource is not found in SMDA
     */
    404: unknown;
    /**
     *
     * SMDA returns valid data but it doesn't meet expected criteria,
     * or no results are found for a valid query.
     *
     */
    422: unknown;
    /**
     *
     * SMDA returns a malformed response that doesn't match
     * the expected structure.
     *
     */
    500: unknown;
    /**
     *
     * An API call to SMDA times out or the service is unavailable.
     *
     */
    503: unknown;
};

export type SmdaPostStratUnitsResponses = {
    /**
     * Successful Response
     */
    200: SmdaStratigraphicUnitsResult;
};

export type SmdaPostStratUnitsResponse = SmdaPostStratUnitsResponses[keyof SmdaPostStratUnitsResponses];

export type SmdaPostWellHeadersData = {
    body: SmdaField;
    path?: never;
    query?: never;
    url: '/api/v1/smda/well_headers';
};

export type SmdaPostWellHeadersErrors = {
    /**
     * Invalid parameters are provided to SMDA API
     */
    400: unknown;
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * A requested resource is not found in SMDA
     */
    404: unknown;
    /**
     *
     * SMDA returns valid data but it doesn't meet expected criteria,
     * or no results are found for a valid query.
     *
     */
    422: unknown;
    /**
     *
     * SMDA returns a malformed response that doesn't match
     * the expected structure.
     *
     */
    500: unknown;
    /**
     *
     * An API call to SMDA times out or the service is unavailable.
     *
     */
    503: unknown;
};

export type SmdaPostWellHeadersResponses = {
    /**
     * Successful Response
     */
    200: SmdaWellHeadersResult;
};

export type SmdaPostWellHeadersResponse = SmdaPostWellHeadersResponses[keyof SmdaPostWellHeadersResponses];

export type MatchPostMatchData = {
    body: MatchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/match';
};

export type MatchPostMatchErrors = {
    /**
     * The request body is missing required match input or contains invalid data.
     */
    422: unknown;
};

export type MatchPostMatchResponses = {
    /**
     * Response Match-Post Match
     *
     * Successful Response
     */
    200: Array<MatchResult>;
};

export type MatchPostMatchResponse = MatchPostMatchResponses[keyof MatchPostMatchResponses];

export type HealthV1HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthV1HealthCheckErrors = {
    /**
     * No active or valid session was found
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Something unexpected has happened
     */
    500: unknown;
};

export type HealthV1HealthCheckError = HealthV1HealthCheckErrors[keyof HealthV1HealthCheckErrors];

export type HealthV1HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: Ok;
};

export type HealthV1HealthCheckResponse = HealthV1HealthCheckResponses[keyof HealthV1HealthCheckResponses];

export type HealthHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthCheckResponses = {
    /**
     * Successful Response
     */
    200: Ok;
};

export type HealthHealthCheckResponse = HealthHealthCheckResponses[keyof HealthHealthCheckResponses];
