// This file is auto-generated by @hey-api/openapi-ts

/**
 * Contains the coordinate system known to SMDA.
 */
export type CoordinateSystem = {
    identifier: string;
    uuid: string;
};

/**
 * A single country in the list of countries known to SMDA.
 */
export type CountryItem = {
    identifier: string;
    uuid: string;
};

/**
 * A single discovery in the list of discoveries known to SMDA.
 */
export type DiscoveryItem = {
    short_identifier: string;
    uuid: string;
};

/**
 * Path where a .fmu directory may exist.
 */
export type FmuDirPath = {
    path: string;
};

/**
 * Information returned when 'opening' an FMU Directory.
 */
export type FmuProject = {
    path: string;
    project_dir_name: string;
    config: ProjectConfig;
};

/**
 * A single field in the list of fields known to SMDA.
 */
export type FieldItem = {
    identifier: string;
    uuid: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * The ``masterdata`` block contains information related to masterdata.
 *
 * Currently, SMDA holds the masterdata.
 */
export type Masterdata = {
    smda?: Smda | null;
};

/**
 * A generic message to return to the GUI.
 */
export type Message = {
    message: string;
};

/**
 * The configuration file in a .fmu directory.
 *
 * Stored as config.json.
 */
export type ProjectConfig = {
    version: string;
    created_at: string;
    created_by: string;
    masterdata: Masterdata;
};

/**
 * Contains SMDA-related attributes.
 */
export type Smda = {
    coordinate_system: CoordinateSystem;
    country: Array<CountryItem>;
    discovery: Array<DiscoveryItem>;
    field: Array<FieldItem>;
    stratigraphic_column: StratigraphicColumn;
};

/**
 * Contains the stratigraphic column known to SMDA.
 */
export type StratigraphicColumn = {
    identifier: string;
    uuid: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type V1DeleteFmuDirectorySessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/fmu/';
};

export type V1DeleteFmuDirectorySessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type V1DeleteFmuDirectorySessionError = V1DeleteFmuDirectorySessionErrors[keyof V1DeleteFmuDirectorySessionErrors];

export type V1DeleteFmuDirectorySessionResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type V1DeleteFmuDirectorySessionResponse = V1DeleteFmuDirectorySessionResponses[keyof V1DeleteFmuDirectorySessionResponses];

export type V1GetCwdFmuDirectorySessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/fmu/';
};

export type V1GetCwdFmuDirectorySessionResponses = {
    /**
     * Successful Response
     */
    200: FmuProject;
};

export type V1GetCwdFmuDirectorySessionResponse = V1GetCwdFmuDirectorySessionResponses[keyof V1GetCwdFmuDirectorySessionResponses];

export type V1GetFmuDirectorySessionData = {
    body: FmuDirPath;
    path?: never;
    query?: never;
    url: '/api/v1/fmu/';
};

export type V1GetFmuDirectorySessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type V1GetFmuDirectorySessionError = V1GetFmuDirectorySessionErrors[keyof V1GetFmuDirectorySessionErrors];

export type V1GetFmuDirectorySessionResponses = {
    /**
     * Successful Response
     */
    200: FmuProject;
};

export type V1GetFmuDirectorySessionResponse = V1GetFmuDirectorySessionResponses[keyof V1GetFmuDirectorySessionResponses];

export type V1InitFmuDirectorySessionData = {
    body: FmuDirPath;
    path?: never;
    query?: never;
    url: '/api/v1/fmu/init';
};

export type V1InitFmuDirectorySessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type V1InitFmuDirectorySessionError = V1InitFmuDirectorySessionErrors[keyof V1InitFmuDirectorySessionErrors];

export type V1InitFmuDirectorySessionResponses = {
    /**
     * Successful Response
     */
    200: FmuProject;
};

export type V1InitFmuDirectorySessionResponse = V1InitFmuDirectorySessionResponses[keyof V1InitFmuDirectorySessionResponses];

export type V1GetFmuDirectoryConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/config/';
};

export type V1GetFmuDirectoryConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type V1GetFmuDirectoryConfigError = V1GetFmuDirectoryConfigErrors[keyof V1GetFmuDirectoryConfigErrors];

export type V1GetFmuDirectoryConfigResponses = {
    /**
     * Successful Response
     */
    200: ProjectConfig;
};

export type V1GetFmuDirectoryConfigResponse = V1GetFmuDirectoryConfigResponses[keyof V1GetFmuDirectoryConfigResponses];

export type V1V1HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type V1V1HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type V1V1HealthCheckResponse = V1V1HealthCheckResponses[keyof V1V1HealthCheckResponses];

export type AppHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type AppHealthCheckResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type AppHealthCheckResponse = AppHealthCheckResponses[keyof AppHealthCheckResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8001' | (string & {});
};