/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProjectIndexRouteImport } from "./routes/project/index";
import { Route as UserRecoveryRouteImport } from "./routes/user/recovery";
import { Route as UserKeysRouteImport } from "./routes/user/keys";
import { Route as ProjectMasterdataRouteImport } from "./routes/project/masterdata";
import { Route as ProjectHistoryRouteImport } from "./routes/project/history";
import { Route as ProjectRmsIndexRouteImport } from "./routes/project/rms/index";
import { Route as ProjectRmsWellboresRouteImport } from "./routes/project/rms/wellbores";
import { Route as ProjectRmsStratigraphyRouteImport } from "./routes/project/rms/stratigraphy";
import { Route as ProjectMappingsWellboresRouteImport } from "./routes/project/mappings/wellbores";
import { Route as ProjectMappingsStratigraphyRouteImport } from "./routes/project/mappings/stratigraphy";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: "/project/",
  path: "/project/",
  getParentRoute: () => rootRouteImport,
} as any);
const UserRecoveryRoute = UserRecoveryRouteImport.update({
  id: "/user/recovery",
  path: "/user/recovery",
  getParentRoute: () => rootRouteImport,
} as any);
const UserKeysRoute = UserKeysRouteImport.update({
  id: "/user/keys",
  path: "/user/keys",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectMasterdataRoute = ProjectMasterdataRouteImport.update({
  id: "/project/masterdata",
  path: "/project/masterdata",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectHistoryRoute = ProjectHistoryRouteImport.update({
  id: "/project/history",
  path: "/project/history",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectRmsIndexRoute = ProjectRmsIndexRouteImport.update({
  id: "/project/rms/",
  path: "/project/rms/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectRmsWellboresRoute = ProjectRmsWellboresRouteImport.update({
  id: "/project/rms/wellbores",
  path: "/project/rms/wellbores",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectRmsStratigraphyRoute = ProjectRmsStratigraphyRouteImport.update({
  id: "/project/rms/stratigraphy",
  path: "/project/rms/stratigraphy",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectMappingsWellboresRoute =
  ProjectMappingsWellboresRouteImport.update({
    id: "/project/mappings/wellbores",
    path: "/project/mappings/wellbores",
    getParentRoute: () => rootRouteImport,
  } as any);
const ProjectMappingsStratigraphyRoute =
  ProjectMappingsStratigraphyRouteImport.update({
    id: "/project/mappings/stratigraphy",
    path: "/project/mappings/stratigraphy",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/project/history": typeof ProjectHistoryRoute;
  "/project/masterdata": typeof ProjectMasterdataRoute;
  "/user/keys": typeof UserKeysRoute;
  "/user/recovery": typeof UserRecoveryRoute;
  "/project/": typeof ProjectIndexRoute;
  "/project/mappings/stratigraphy": typeof ProjectMappingsStratigraphyRoute;
  "/project/mappings/wellbores": typeof ProjectMappingsWellboresRoute;
  "/project/rms/stratigraphy": typeof ProjectRmsStratigraphyRoute;
  "/project/rms/wellbores": typeof ProjectRmsWellboresRoute;
  "/project/rms/": typeof ProjectRmsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/project/history": typeof ProjectHistoryRoute;
  "/project/masterdata": typeof ProjectMasterdataRoute;
  "/user/keys": typeof UserKeysRoute;
  "/user/recovery": typeof UserRecoveryRoute;
  "/project": typeof ProjectIndexRoute;
  "/project/mappings/stratigraphy": typeof ProjectMappingsStratigraphyRoute;
  "/project/mappings/wellbores": typeof ProjectMappingsWellboresRoute;
  "/project/rms/stratigraphy": typeof ProjectRmsStratigraphyRoute;
  "/project/rms/wellbores": typeof ProjectRmsWellboresRoute;
  "/project/rms": typeof ProjectRmsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/project/history": typeof ProjectHistoryRoute;
  "/project/masterdata": typeof ProjectMasterdataRoute;
  "/user/keys": typeof UserKeysRoute;
  "/user/recovery": typeof UserRecoveryRoute;
  "/project/": typeof ProjectIndexRoute;
  "/project/mappings/stratigraphy": typeof ProjectMappingsStratigraphyRoute;
  "/project/mappings/wellbores": typeof ProjectMappingsWellboresRoute;
  "/project/rms/stratigraphy": typeof ProjectRmsStratigraphyRoute;
  "/project/rms/wellbores": typeof ProjectRmsWellboresRoute;
  "/project/rms/": typeof ProjectRmsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/project/history"
    | "/project/masterdata"
    | "/user/keys"
    | "/user/recovery"
    | "/project/"
    | "/project/mappings/stratigraphy"
    | "/project/mappings/wellbores"
    | "/project/rms/stratigraphy"
    | "/project/rms/wellbores"
    | "/project/rms/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/project/history"
    | "/project/masterdata"
    | "/user/keys"
    | "/user/recovery"
    | "/project"
    | "/project/mappings/stratigraphy"
    | "/project/mappings/wellbores"
    | "/project/rms/stratigraphy"
    | "/project/rms/wellbores"
    | "/project/rms";
  id:
    | "__root__"
    | "/"
    | "/project/history"
    | "/project/masterdata"
    | "/user/keys"
    | "/user/recovery"
    | "/project/"
    | "/project/mappings/stratigraphy"
    | "/project/mappings/wellbores"
    | "/project/rms/stratigraphy"
    | "/project/rms/wellbores"
    | "/project/rms/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ProjectHistoryRoute: typeof ProjectHistoryRoute;
  ProjectMasterdataRoute: typeof ProjectMasterdataRoute;
  UserKeysRoute: typeof UserKeysRoute;
  UserRecoveryRoute: typeof UserRecoveryRoute;
  ProjectIndexRoute: typeof ProjectIndexRoute;
  ProjectMappingsStratigraphyRoute: typeof ProjectMappingsStratigraphyRoute;
  ProjectMappingsWellboresRoute: typeof ProjectMappingsWellboresRoute;
  ProjectRmsStratigraphyRoute: typeof ProjectRmsStratigraphyRoute;
  ProjectRmsWellboresRoute: typeof ProjectRmsWellboresRoute;
  ProjectRmsIndexRoute: typeof ProjectRmsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project/": {
      id: "/project/";
      path: "/project";
      fullPath: "/project/";
      preLoaderRoute: typeof ProjectIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/user/recovery": {
      id: "/user/recovery";
      path: "/user/recovery";
      fullPath: "/user/recovery";
      preLoaderRoute: typeof UserRecoveryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/user/keys": {
      id: "/user/keys";
      path: "/user/keys";
      fullPath: "/user/keys";
      preLoaderRoute: typeof UserKeysRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project/masterdata": {
      id: "/project/masterdata";
      path: "/project/masterdata";
      fullPath: "/project/masterdata";
      preLoaderRoute: typeof ProjectMasterdataRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project/history": {
      id: "/project/history";
      path: "/project/history";
      fullPath: "/project/history";
      preLoaderRoute: typeof ProjectHistoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project/rms/": {
      id: "/project/rms/";
      path: "/project/rms";
      fullPath: "/project/rms/";
      preLoaderRoute: typeof ProjectRmsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project/rms/wellbores": {
      id: "/project/rms/wellbores";
      path: "/project/rms/wellbores";
      fullPath: "/project/rms/wellbores";
      preLoaderRoute: typeof ProjectRmsWellboresRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project/rms/stratigraphy": {
      id: "/project/rms/stratigraphy";
      path: "/project/rms/stratigraphy";
      fullPath: "/project/rms/stratigraphy";
      preLoaderRoute: typeof ProjectRmsStratigraphyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project/mappings/wellbores": {
      id: "/project/mappings/wellbores";
      path: "/project/mappings/wellbores";
      fullPath: "/project/mappings/wellbores";
      preLoaderRoute: typeof ProjectMappingsWellboresRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project/mappings/stratigraphy": {
      id: "/project/mappings/stratigraphy";
      path: "/project/mappings/stratigraphy";
      fullPath: "/project/mappings/stratigraphy";
      preLoaderRoute: typeof ProjectMappingsStratigraphyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectHistoryRoute: ProjectHistoryRoute,
  ProjectMasterdataRoute: ProjectMasterdataRoute,
  UserKeysRoute: UserKeysRoute,
  UserRecoveryRoute: UserRecoveryRoute,
  ProjectIndexRoute: ProjectIndexRoute,
  ProjectMappingsStratigraphyRoute: ProjectMappingsStratigraphyRoute,
  ProjectMappingsWellboresRoute: ProjectMappingsWellboresRoute,
  ProjectRmsStratigraphyRoute: ProjectRmsStratigraphyRoute,
  ProjectRmsWellboresRoute: ProjectRmsWellboresRoute,
  ProjectRmsIndexRoute: ProjectRmsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
