/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProjectIndexRouteImport } from "./routes/project/index";
import { Route as UserRecoveryRouteImport } from "./routes/user/recovery";
import { Route as UserKeysRouteImport } from "./routes/user/keys";
import { Route as ProjectStratigraphyRouteImport } from "./routes/project/stratigraphy";
import { Route as ProjectRmsRouteImport } from "./routes/project/rms";
import { Route as ProjectMasterdataRouteImport } from "./routes/project/masterdata";
import { Route as ProjectHistoryRouteImport } from "./routes/project/history";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: "/project/",
  path: "/project/",
  getParentRoute: () => rootRouteImport,
} as any);
const UserRecoveryRoute = UserRecoveryRouteImport.update({
  id: "/user/recovery",
  path: "/user/recovery",
  getParentRoute: () => rootRouteImport,
} as any);
const UserKeysRoute = UserKeysRouteImport.update({
  id: "/user/keys",
  path: "/user/keys",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectStratigraphyRoute = ProjectStratigraphyRouteImport.update({
  id: "/project/stratigraphy",
  path: "/project/stratigraphy",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectRmsRoute = ProjectRmsRouteImport.update({
  id: "/project/rms",
  path: "/project/rms",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectMasterdataRoute = ProjectMasterdataRouteImport.update({
  id: "/project/masterdata",
  path: "/project/masterdata",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectHistoryRoute = ProjectHistoryRouteImport.update({
  id: "/project/history",
  path: "/project/history",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/project/history": typeof ProjectHistoryRoute;
  "/project/masterdata": typeof ProjectMasterdataRoute;
  "/project/rms": typeof ProjectRmsRoute;
  "/project/stratigraphy": typeof ProjectStratigraphyRoute;
  "/user/keys": typeof UserKeysRoute;
  "/user/recovery": typeof UserRecoveryRoute;
  "/project/": typeof ProjectIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/project/history": typeof ProjectHistoryRoute;
  "/project/masterdata": typeof ProjectMasterdataRoute;
  "/project/rms": typeof ProjectRmsRoute;
  "/project/stratigraphy": typeof ProjectStratigraphyRoute;
  "/user/keys": typeof UserKeysRoute;
  "/user/recovery": typeof UserRecoveryRoute;
  "/project": typeof ProjectIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/project/history": typeof ProjectHistoryRoute;
  "/project/masterdata": typeof ProjectMasterdataRoute;
  "/project/rms": typeof ProjectRmsRoute;
  "/project/stratigraphy": typeof ProjectStratigraphyRoute;
  "/user/keys": typeof UserKeysRoute;
  "/user/recovery": typeof UserRecoveryRoute;
  "/project/": typeof ProjectIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/project/history"
    | "/project/masterdata"
    | "/project/rms"
    | "/project/stratigraphy"
    | "/user/keys"
    | "/user/recovery"
    | "/project/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/project/history"
    | "/project/masterdata"
    | "/project/rms"
    | "/project/stratigraphy"
    | "/user/keys"
    | "/user/recovery"
    | "/project";
  id:
    | "__root__"
    | "/"
    | "/project/history"
    | "/project/masterdata"
    | "/project/rms"
    | "/project/stratigraphy"
    | "/user/keys"
    | "/user/recovery"
    | "/project/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ProjectHistoryRoute: typeof ProjectHistoryRoute;
  ProjectMasterdataRoute: typeof ProjectMasterdataRoute;
  ProjectRmsRoute: typeof ProjectRmsRoute;
  ProjectStratigraphyRoute: typeof ProjectStratigraphyRoute;
  UserKeysRoute: typeof UserKeysRoute;
  UserRecoveryRoute: typeof UserRecoveryRoute;
  ProjectIndexRoute: typeof ProjectIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project/": {
      id: "/project/";
      path: "/project";
      fullPath: "/project/";
      preLoaderRoute: typeof ProjectIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/user/recovery": {
      id: "/user/recovery";
      path: "/user/recovery";
      fullPath: "/user/recovery";
      preLoaderRoute: typeof UserRecoveryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/user/keys": {
      id: "/user/keys";
      path: "/user/keys";
      fullPath: "/user/keys";
      preLoaderRoute: typeof UserKeysRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project/stratigraphy": {
      id: "/project/stratigraphy";
      path: "/project/stratigraphy";
      fullPath: "/project/stratigraphy";
      preLoaderRoute: typeof ProjectStratigraphyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project/rms": {
      id: "/project/rms";
      path: "/project/rms";
      fullPath: "/project/rms";
      preLoaderRoute: typeof ProjectRmsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project/masterdata": {
      id: "/project/masterdata";
      path: "/project/masterdata";
      fullPath: "/project/masterdata";
      preLoaderRoute: typeof ProjectMasterdataRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/project/history": {
      id: "/project/history";
      path: "/project/history";
      fullPath: "/project/history";
      preLoaderRoute: typeof ProjectHistoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectHistoryRoute: ProjectHistoryRoute,
  ProjectMasterdataRoute: ProjectMasterdataRoute,
  ProjectRmsRoute: ProjectRmsRoute,
  ProjectStratigraphyRoute: ProjectStratigraphyRoute,
  UserKeysRoute: UserKeysRoute,
  UserRecoveryRoute: UserRecoveryRoute,
  ProjectIndexRoute: ProjectIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
