name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    if: ${{ !github.event.release.prerelease }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fmu-settings-gui
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout commit locally
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      with:
        fetch-depth: 0

    - name: Set up Python 3.12
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: 3.12

    - name: Install pnpm
      uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
      with:
        version: 10
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 22

    - name: Install build dependencies
      run: |
        pip install -U pip
        pip install build

    - name: Build distributions
      run: python -m build -vv

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
